/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import DAO.EmprestimoDAO;
import DAO.LivroDAO;
import java.awt.Color;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static main.main.alunoLogado;
import static main.main.identificacao;
import model.Emprestimo;
import model.Livro;

/**
 *
 * @author Jorge Lucas
 */
public class TelaAluno extends javax.swing.JFrame {

    /**
     * Creates new form TelaBibliotecario
     */
    public TelaAluno() {
        initComponents();
        configurarBemVindo();
        configurarTabelaLivro();
        limparTabelaLivro();
        limparTabelaEmprestimo();
        inserirNaTabelaLivro();
        inserirNaTabelaEmprestimo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbLivros = new javax.swing.JTable();
        jBAlugar = new javax.swing.JButton();
        jLProcurar = new javax.swing.JLabel();
        jCBLivro = new javax.swing.JComboBox<>();
        jTFProcurarLivro = new javax.swing.JTextField();
        jLLupaLivro = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbEmprestimos = new javax.swing.JTable();
        jBRenovar = new javax.swing.JButton();
        jBDevolver = new javax.swing.JButton();
        jLBemVindo = new javax.swing.JLabel();
        jLSair = new javax.swing.JLabel();
        livroicon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jTabbedPane3.setBackground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(255, 204, 102));

        jTbLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Descrição", "Qtd"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTbLivros);

        jBAlugar.setText("Alugar");
        jBAlugar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlugarActionPerformed(evt);
            }
        });

        jLProcurar.setText("Procurar:");

        jCBLivro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione ...", "Título", "Descrição" }));

        jLLupaLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/lupa.png"))); // NOI18N
        jLLupaLivro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLLupaLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLLupaLivroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLProcurar)
                        .addGap(18, 18, 18)
                        .addComponent(jTFProcurarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLLupaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jCBLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(jBAlugar, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTFProcurarLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLProcurar)
                        .addComponent(jCBLivro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLLupaLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jBAlugar)
                .addGap(30, 30, 30))
        );

        jTabbedPane3.addTab("Livros Disponíveis", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 102));

        jTbEmprestimos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Descrição", "Data de Inicio", "Data de Fim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTbEmprestimos);

        jBRenovar.setBackground(new java.awt.Color(255, 255, 255));
        jBRenovar.setText("Renovar");
        jBRenovar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBRenovarActionPerformed(evt);
            }
        });

        jBDevolver.setBackground(new java.awt.Color(255, 255, 255));
        jBDevolver.setText("Devolver");
        jBDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDevolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jBDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBRenovar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBRenovar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        jTabbedPane3.addTab("Meus Empréstimos", jPanel2);

        jLBemVindo.setBackground(new java.awt.Color(255, 204, 102));
        jLBemVindo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLBemVindo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLBemVindo.setText("Olá Aluno(a) ");
        jLBemVindo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(255, 204, 102), new java.awt.Color(255, 204, 102)));

        jLSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLSair.setText("Sair");
        jLSair.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLSairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLSairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLSairMouseExited(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLSairMouseReleased(evt);
            }
        });

        livroicon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/open-book.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane3)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(livroicon)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addComponent(jLSair, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLBemVindo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLSair, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(livroicon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)))
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane3.getAccessibleContext().setAccessibleName("Livros Disponíveis");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void configurarTabelaLivro(){
  
        jTbLivros.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTbLivros.getColumnModel().getColumn(1).setPreferredWidth(300);
        jTbLivros.getColumnModel().getColumn(2).setPreferredWidth(25);
        
        jTbEmprestimos.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTbEmprestimos.getColumnModel().getColumn(1).setPreferredWidth(200);
        jTbEmprestimos.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTbEmprestimos.getColumnModel().getColumn(2).setPreferredWidth(100);
    
    }
    
 
    private void inserirNaTabelaLivroCom(){
        String nomeDesejado = jTFProcurarLivro.getText().toLowerCase();
       
         
        DefaultTableModel tabela = (DefaultTableModel) jTbLivros.getModel();
        
        
        if(jCBLivro.getSelectedItem().equals("Título")){
          for(Livro livroAtual : new LivroDAO().getList()){
                Object[] linha ={livroAtual.getTitulo(),
                                 livroAtual.getDescricaoDoLivro(),
                                 livroAtual.getQuantidadeLivro()};
                if(livroAtual.getTitulo().toLowerCase().contains(nomeDesejado))
                    tabela.addRow(linha);
                    
            }  
        }
        
        if(jCBLivro.getSelectedItem().equals("Descrição")){
          for(Livro livroAtual : new LivroDAO().getList()){
                Object[] linha ={livroAtual.getTitulo(),
                                 livroAtual.getDescricaoDoLivro(),
                                 livroAtual.getQuantidadeLivro()};
                if(livroAtual.getDescricaoDoLivro().toLowerCase().contains(nomeDesejado))
                    tabela.addRow(linha);
                    
            }  
        }      
            
    }
    
    private void inserirNaTabelaEmprestimo(){
        DefaultTableModel tabela = (DefaultTableModel) jTbEmprestimos.getModel();
            for(Emprestimo emprestimoAtual : new EmprestimoDAO().emprestimoAluno(alunoLogado)){
                Object[] linha ={emprestimoAtual.getLivro().getTitulo(),
                                 emprestimoAtual.getLivro().getDescricaoDoLivro(),
                                 emprestimoAtual.getDataInicio(),
                                 emprestimoAtual.getDataTermino()};
                tabela.addRow(linha);
                    
            }
    }
    private void inserirNaTabelaLivro(){
        DefaultTableModel tabela = (DefaultTableModel) jTbLivros.getModel();
            for(Livro livroAtual : new LivroDAO().getList()){
                Object[] linha ={livroAtual.getTitulo(),
                                 livroAtual.getDescricaoDoLivro(),
                                 livroAtual.getQuantidadeLivro()};
                tabela.addRow(linha);
                    
            }                
    }
    
 
    private void limparTabelaEmprestimo(){
        DefaultTableModel tabela = (DefaultTableModel) jTbEmprestimos.getModel();
        tabela.setNumRows(0);
    }
    private void limparTabelaLivro(){
        DefaultTableModel tabela = (DefaultTableModel) jTbLivros.getModel();
        tabela.setNumRows(0);
    }
    private void configurarBemVindo(){
        jLBemVindo.setText(""+jLBemVindo.getText()+identificacao+"");
    }
    private void jLSairMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSairMouseReleased

    }//GEN-LAST:event_jLSairMouseReleased

    private void jLSairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSairMouseEntered
        jLSair.setForeground(Color.blue);
        jLSair.setText("<html><u>Sair</u>");
    }//GEN-LAST:event_jLSairMouseEntered

    private void jLSairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSairMouseExited
        jLSair.setForeground(Color.black);
        jLSair.setText("Sair");
    }//GEN-LAST:event_jLSairMouseExited

    private void jLSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLSairMouseClicked
        new telaLogin1().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLSairMouseClicked

    private void jBAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlugarActionPerformed
        if(jTbLivros.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione um Livro",null,JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(jTbLivros.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(null, "Selecione apenas um Livro",null,JOptionPane.ERROR_MESSAGE);
            return;
        }
        Livro livroAlugar = new LivroDAO().livroPorTitulo((String)jTbLivros.getValueAt(jTbLivros.getSelectedRow(), 0));
        
        if(new EmprestimoDAO().podeFazerEmprestimo(alunoLogado)){
            new EmprestimoDAO().adicionarEmprestimo(livroAlugar, alunoLogado, new Date());
            limparTabelaLivro();
            inserirNaTabelaLivro();
            limparTabelaEmprestimo();
            inserirNaTabelaEmprestimo();
        }else {
           JOptionPane.showMessageDialog(null, "Já ultrapassou o limite de livros alugados",null,JOptionPane.ERROR_MESSAGE); 
        }
        
        
        
        

    }//GEN-LAST:event_jBAlugarActionPerformed

    private void jLLupaLivroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLLupaLivroMouseClicked
        limparTabelaLivro();
        if(jTFProcurarLivro.getText().equals(""))
            inserirNaTabelaLivro();
        else if(jCBLivro.getSelectedItem().equals("Selecione ..."))
            JOptionPane.showMessageDialog(null, "Selecione uma opção",null,JOptionPane.ERROR_MESSAGE);
        else
            inserirNaTabelaLivroCom();
    }//GEN-LAST:event_jLLupaLivroMouseClicked

    private void jBDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDevolverActionPerformed
        if(jTbEmprestimos.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione um Livro",null,JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(jTbEmprestimos.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(null, "Selecione apenas um Livro",null,JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Livro l = new LivroDAO().livroPorTitulo((String)jTbEmprestimos.getValueAt(jTbEmprestimos.getSelectedRow(), 0));
        
        new EmprestimoDAO().removerEmprestimo(l, alunoLogado, (Date)jTbEmprestimos.getValueAt(jTbEmprestimos.getSelectedRow(), 2));
        limparTabelaEmprestimo();
        inserirNaTabelaEmprestimo();
        limparTabelaLivro();
        inserirNaTabelaLivro();
    }//GEN-LAST:event_jBDevolverActionPerformed

    private void jBRenovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBRenovarActionPerformed
        if(jTbEmprestimos.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Selecione um Livro",null,JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(jTbEmprestimos.getSelectedRowCount() > 1){
            JOptionPane.showMessageDialog(null, "Selecione apenas um Livro",null,JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        Livro l = new LivroDAO().livroPorTitulo((String)jTbEmprestimos.getValueAt(jTbEmprestimos.getSelectedRow(), 0));
        
        new EmprestimoDAO().renovarEmprestimo(alunoLogado, l, (Date)jTbEmprestimos.getValueAt(jTbEmprestimos.getSelectedRow(), 2));
        limparTabelaEmprestimo();
        inserirNaTabelaEmprestimo();
        limparTabelaLivro();
        inserirNaTabelaLivro();
    }//GEN-LAST:event_jBRenovarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlugar;
    private javax.swing.JButton jBDevolver;
    private javax.swing.JButton jBRenovar;
    private javax.swing.JComboBox<String> jCBLivro;
    private javax.swing.JLabel jLBemVindo;
    private javax.swing.JLabel jLLupaLivro;
    private javax.swing.JLabel jLProcurar;
    private javax.swing.JLabel jLSair;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFProcurarLivro;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTable jTbEmprestimos;
    private javax.swing.JTable jTbLivros;
    private javax.swing.JLabel livroicon;
    // End of variables declaration//GEN-END:variables
}
